function p=userpath()
% USERPATH - Defines the paths used in this project
%    p=userpath()
%    
%    Return values:
%      p: path array

p = [...
     'src:',...
     'src/model:',...
     'src/inputs:',...
     'src/auxiliary:',...
     'src/examples:',...
    ];

